include:
  - local: templates/python/Python.gitlab-ci.yml
  - local: templates/node/Node.gitlab-ci.yml
  - local: templates/python-node/PythonNode.gitlab-ci.yml
  - local: templates/postgis/PostGIS.gitlab-ci.yml

variables:
  # Docker by default users `vfs` which is not suitable for
  # production use. overlay2 is the preferred driver by Docker.
  DOCKER_DRIVER: overlay2

  # TODO: Fix me
  # Ref: https://about.gitlab.com/2019/07/31/docker-in-docker-with-docker-19-dot-03/
  DOCKER_TLS_CERTDIR: ""


stages:
  - build
  - secondary_build

before_script:
  - source setup.sh
  - source helpers.sh
  - set_docker_host
