include:
  - local: templates/python/Python.gitlab-ci.yml
  - local: templates/node/Node.gitlab-ci.yml
  - local: templates/python-node/PythonNode.gitlab-ci.yml
  - local: templates/postgis/PostGIS.gitlab-ci.yml

variables:
  # Docker by default users `vfs` which is not suitable for
  # production use. overlay2 is the preferred driver by Docker.
  DOCKER_DRIVER: overlay2

  # If the host is not set docker cli will try to use a 172.x.x.x
  # IP when connecting to the Docker API, which will not work
  DOCKER_HOST: "tcp://localhost:2375"

  # TODO: Fix me
  # Ref: https://about.gitlab.com/2019/07/31/docker-in-docker-with-docker-19-dot-03/
  DOCKER_TLS_CERTDIR: ""

  # Use BuildKit when creating docker images
  DOCKER_BUILDKIT: 1


stages:
  - build
  - secondary_build
