.build-python:
  stage: build
  image: docker:stable-git
  services:
    - docker:stable-dind
  variables:
    TEMPLATE: "python"
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - base_image="$TEMPLATE:$VERSION-$VARIANT"
    - image="$CI_REGISTRY_IMAGE/$base_image"
    - cd "templates/$TEMPLATE"
    - docker build --build-arg BUILD_FROM="$base_image" --build-arg SSH_PRIVATE_KEY="$SSH_PRIVATE_KEY" --build-arg SSH_PUBLIC_KEY="$SSH_PUBLIC_KEY" --pull -t "$image" .
    - docker push "$image"
  only:
    - master
  except:
    variables:
      - $PYTHON_DISABLED

build-python-3.6:
  variables:
    VERSION: "3.6"
    VARIANT: "slim"
  extends: .build-python

build-python-3.7:
  variables:
    VERSION: "3.7"
    VARIANT: "slim"
  extends: .build-python
