.build-python-node:
  stage: secondary_build
  image: docker:stable
  services:
    - docker:stable-dind
  variables:
    TEMPLATE: "python-node"
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - base_image="$CI_REGISTRY_IMAGE/python:$PYTHON_VERSION-$VARIANT"
    - image="$CI_REGISTRY_IMAGE/$TEMPLATE:$PYTHON_VERSION-${NODE_VERSION%%.*}-$VARIANT"
    - cd "templates/$TEMPLATE"
    - docker build --build-arg BUILD_FROM="$base_image" --build-arg NODE_VERSION="$NODE_VERSION" -t "$image" .
    - docker push "$image"
  only:
    - master
  except:
    variables:
      - $PYTHON_NODE_DISABLED

build-python-3.6-node-8:
  variables:
    PYTHON_VERSION: "3.6"
    NODE_VERSION: "8.16.1"
    VARIANT: "slim"
  extends: .build-python-node

build-python-3.6-node-10:
  variables:
    PYTHON_VERSION: "3.6"
    NODE_VERSION: "10.16.3"
    VARIANT: "slim"
  extends: .build-python-node

build-python-3.6-node-12:
  variables:
    PYTHON_VERSION: "3.6"
    NODE_VERSION: "12.10.0"
    VARIANT: "slim"
  extends: .build-python-node

build-python-3.7-node-8:
  variables:
    PYTHON_VERSION: "3.7"
    NODE_VERSION: "8.16.1"
    VARIANT: "slim"
  extends: .build-python-node

build-python-3.7-node-10:
  variables:
    PYTHON_VERSION: "3.7"
    NODE_VERSION: "10.16.3"
    VARIANT: "slim"
  extends: .build-python-node

build-python-3.7-node-12:
  variables:
    PYTHON_VERSION: "3.7"
    NODE_VERSION: "12.10.0"
    VARIANT: "slim"
  extends: .build-python-node
